--- # devspaces.yml
name: mezzanine
description:  Development environment for Mezzanine SCM

# If you want to use a different Dockerfile for your DevSpace, provide the path
# here.
docker-file: Dockerfile

# If you need additional files when building your Dockerfile, such as some
# application binaries that your Dockerfile references, list the glob paths to
# include here. They are relative to this devspaces.yml file.
docker-build-includes: |
  **/*
ports:
- protocol: http # can be udp|tcp|http
  port-number: 8000
  description: web app http port

# generic `build` filter cannot be used once we have a source package named `build`.
sync-ignore: |
  .git
  .idea
  **/node_modules
  .DS_Store
  .data
  *.pyc
